import {
  Shield, LayoutDashboard, ShieldAlert, FileText, Settings, Plus,
  AlertTriangle, CheckCircle, XCircle, Eye, ArrowUpRight, Download,
  Maximize2, X, ChevronRight, ChevronDown, RotateCcw, Check,
  Clock, MapPin, Camera, User, Activity, BarChart2, List, Columns,
  Info, AlertCircle, Zap, Radio, Cpu, Bug, Bell, Globe, Key,
  Terminal, Play, Pause, RefreshCw, Filter, SortDesc, SortAsc,
  Clipboard, Star, Archive, Trash2, Edit2, ExternalLink, Lock,
  Unlock, Database, Server, Wifi, WifiOff, Monitor, Hash,
  MoreHorizontal, BookOpen, Layers, TrendingUp, TrendingDown,
  PieChart, BarChart, LineChart, Map, Navigation,
  Sparkles, Home, FileCheck, Construction, Video, Image, ScanEye,
} from 'lucide-react';

const ICON_MAP = {
  'shield': Shield,
  'layout-dashboard': LayoutDashboard,
  'shield-alert': ShieldAlert,
  'file-text': FileText,
  'settings': Settings,
  'plus': Plus,
  'alert-triangle': AlertTriangle,
  'check-circle': CheckCircle,
  'x-circle': XCircle,
  'eye': Eye,
  'arrow-up-right': ArrowUpRight,
  'download': Download,
  'maximize-2': Maximize2,
  'x': X,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  'rotate-ccw': RotateCcw,
  'check': Check,
  'clock': Clock,
  'map-pin': MapPin,
  'camera': Camera,
  'user': User,
  'activity': Activity,
  'bar-chart-2': BarChart2,
  'list': List,
  'columns': Columns,
  'info': Info,
  'alert-circle': AlertCircle,
  'zap': Zap,
  'radio': Radio,
  'cpu': Cpu,
  'bug': Bug,
  'bell': Bell,
  'globe': Globe,
  'key': Key,
  'terminal': Terminal,
  'play': Play,
  'pause': Pause,
  'refresh-cw': RefreshCw,
  'filter': Filter,
  'sort-desc': SortDesc,
  'sort-asc': SortAsc,
  'clipboard': Clipboard,
  'star': Star,
  'archive': Archive,
  'trash-2': Trash2,
  'edit-2': Edit2,
  'external-link': ExternalLink,
  'lock': Lock,
  'unlock': Unlock,
  'database': Database,
  'server': Server,
  'wifi': Wifi,
  'wifi-off': WifiOff,
  'monitor': Monitor,
  'hash': Hash,
  'more-horizontal': MoreHorizontal,
  'book-open': BookOpen,
  'layers': Layers,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'pie-chart': PieChart,
  'bar-chart': BarChart,
  'line-chart': LineChart,
  'map': Map,
  'navigation': Navigation,
  'sparkles': Sparkles,
  'home': Home,
  'file-check': FileCheck,
  'construction': Construction,
  'video': Video,
  'image': Image,
  'scan-eye': ScanEye,
};

export default function Icon({ name, size = 16, color, style: sx = {} }) {
  const LucideIcon = ICON_MAP[name];
  if (!LucideIcon) return null;
  return (
    <span style={{ display: 'inline-flex', alignItems: 'center', flexShrink: 0, ...sx }}>
      <LucideIcon size={size} color={color} strokeWidth={1.5} />
    </span>
  );
}
